### PR TITLE
Dotnet next

### PR DESCRIPTION
**Pull request by hikalkan**
* Renamed projects from Castle to Fortress.
* Added Powershell script to create nuget packages.
* Made version 0.5. for initial release.

### CODE REVIEW

**Comment by fir3pho3nixx** [comment]
Hi, is it ok if I move the nuget packing to fsharp? Also will get this published tonight.

**Comment by fir3pho3nixx** [comment]
Dont know fsharp? Dont worry nobody does! We all pretend, some are just better than others :)

**Comment by hikalkan** [comment]
I fixed assembly name in unit test: https://github.com/cryosharp/fortress/pull/21/commits/bf33eae196768c6e49b77974667cd1c9bb563fcb

**Comment by fir3pho3nixx** [comment]
Thanks use this as a guide, re-implemented on master ...

**Pull request closed without merging**
